"""Typed MC03 domain contracts, value objects, errors, and audit helpers."""

from mc03.domain.audit import build_lineage_audit_payload, build_safe_audit_payload
from mc03.domain.errors import DAError, ErrorCode, ImmutableMutationError, MC03Error
from mc03.domain.hierarchy import (
    INFORMANT_RELATIONS,
    NOISE_REMARK_VALUES,
    NOISE_STATUS_VALUES,
    REPRESENTATIVE_RELATIONS,
    ExclusionClassificationResult,
    RelationClassificationResult,
    classify_exclusion,
    classify_relation,
    classify_relation_result,
    csu_rank,
    is_ambiguous_informant,
    is_defined_noise,
    is_representative_refused_eligible,
    select_rfd,
)
from mc03.domain.models import (
    ArtifactRecord,
    ArtifactStatus,
    ArtifactType,
    AuditEvent,
    ConfigurationSnapshot,
    Disposition,
    ExceptionKind,
    ExclusionKind,
    OutcomeDisposition,
    ProcessedRow,
    ProcessingOutcome,
    RawSourceRecord,
    Relation,
    RemarkFields,
    ReportRun,
    RunResult,
    RunState,
    RunStateEvent,
)
from mc03.domain.remarks import (
    RemarkExtractionResult,
    RemarkGateway,
    extract_remark,
    trim_to_200,
)
from mc03.domain.sanitizer import sanitize_remark

__all__ = [
    "ArtifactRecord",
    "ArtifactStatus",
    "ArtifactType",
    "AuditEvent",
    "ConfigurationSnapshot",
    "DAError",
    "Disposition",
    "ErrorCode",
    "ExceptionKind",
    "ExclusionClassificationResult",
    "ExclusionKind",
    "ImmutableMutationError",
    "INFORMANT_RELATIONS",
    "MC03Error",
    "NOISE_REMARK_VALUES",
    "NOISE_STATUS_VALUES",
    "OutcomeDisposition",
    "ProcessedRow",
    "ProcessingOutcome",
    "RawSourceRecord",
    "REPRESENTATIVE_RELATIONS",
    "Relation",
    "RelationClassificationResult",
    "RemarkExtractionResult",
    "RemarkFields",
    "RemarkGateway",
    "ReportRun",
    "RunResult",
    "RunState",
    "RunStateEvent",
    "build_lineage_audit_payload",
    "classify_exclusion",
    "classify_relation",
    "classify_relation_result",
    "csu_rank",
    "extract_remark",
    "is_ambiguous_informant",
    "is_defined_noise",
    "is_representative_refused_eligible",
    "sanitize_remark",
    "select_rfd",
    "trim_to_200",
    "build_safe_audit_payload",
]
